services:
  master:
    image: cituswithpgpartmandocker:latest
    container_name: citus_master
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - master_data:/var/lib/postgresql/data

  worker:
    image: cituswithpgpartmandocker:latest
    depends_on:
      - master
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    volumes:
      - worker_data:/var/lib/postgresql/data

volumes:
  master_data:
  worker_data:
