name: Build Docker Image On Tag Push

env:
  DOCKERHUB_USER_NAME: ${{ secrets.DOCKERHUB_USER_NAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_and_publish_images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_type:
          - latest
          - alpine
          - postgres_14
          - nightly

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Clone tools branch
        run: git clone -b v0.8.30 --depth=1 https://github.com/citusdata/tools.git tools

      - name: Install package dependencies
        run: sudo apt-get update && sudo apt install -y libcurl4-openssl-dev libssl-dev python3-testresources

      - name: Install python requirements
        run: python -m pip install -r tools/packaging_automation/requirements.txt

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: DockerHub Login
        run: docker login -u "${DOCKERHUB_USER_NAME}" -p "${DOCKERHUB_PASSWORD}"

      - name: Build and publish docker images
        run: |
          python -m tools.packaging_automation.publish_docker \
            --github_ref "${GITHUB_REF}" \
            --pipeline_trigger_type "${GITHUB_EVENT_NAME}" \
            --image_type "${{ matrix.image_type }}"
        env:
          DOCKER_BUILDKIT: 1
          BUILDX_PLATFORM: "linux/amd64,linux/arm64"
